"""modifying

Revision ID: 3cdfc8173d26
Revises: 855ae23722ca
Create Date: 2022-02-18 10:35:06.208449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdfc8173d26'
down_revision = '855ae23722ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_link', sa.String(length=500), nullable=True),
    sa.Column('week_day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['week_day_id'], ['week_day_relation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_id'), 'schedule', ['id'], unique=False)
    op.drop_constraint('week_day_relation_week_day_id_fkey', 'week_day_relation', type_='foreignkey')
    op.drop_column('week_day_relation', 'week_day_id')
    op.drop_column('week_day_relation', 'json_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_day_relation', sa.Column('json_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('week_day_relation', sa.Column('week_day_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('week_day_relation_week_day_id_fkey', 'week_day_relation', 'week_day_relation', ['week_day_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_schedule_id'), table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###
