"""modifying

Revision ID: 855ae23722ca
Revises: 
Create Date: 2022-02-18 10:23:48.684522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855ae23722ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body-type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body-type_id'), 'body-type', ['id'], unique=False)
    op.create_table('day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_id'), 'day', ['id'], unique=False)
    op.create_table('my-profile-user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=250), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('BMI', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_my-profile-user_email'), 'my-profile-user', ['email'], unique=True)
    op.create_index(op.f('ix_my-profile-user_id'), 'my-profile-user', ['id'], unique=False)
    op.create_table('week',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_week_id'), 'week', ['id'], unique=False)
    op.create_table('week_day_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('json_link', sa.String(length=500), nullable=True),
    sa.Column('week_day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_day_id'], ['week_day_relation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['week.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_week_day_relation_id'), 'week_day_relation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_week_day_relation_id'), table_name='week_day_relation')
    op.drop_table('week_day_relation')
    op.drop_index(op.f('ix_week_id'), table_name='week')
    op.drop_table('week')
    op.drop_index(op.f('ix_my-profile-user_id'), table_name='my-profile-user')
    op.drop_index(op.f('ix_my-profile-user_email'), table_name='my-profile-user')
    op.drop_table('my-profile-user')
    op.drop_index(op.f('ix_day_id'), table_name='day')
    op.drop_table('day')
    op.drop_index(op.f('ix_body-type_id'), table_name='body-type')
    op.drop_table('body-type')
    # ### end Alembic commands ###
