"""foreign_key

Revision ID: 96dee4e540d4
Revises: d77e08362c12
Create Date: 2022-02-23 08:56:44.513911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96dee4e540d4'
down_revision = 'd77e08362c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
