"""meal plan

Revision ID: ab74d7418598
Revises: 96dee4e540d4
Create Date: 2022-02-23 08:59:06.623786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab74d7418598'
down_revision = '96dee4e540d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
