"""new table

Revision ID: b6e2546e1c6a
Revises: f1199a27af80
Create Date: 2022-02-18 11:32:43.548492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e2546e1c6a'
down_revision = 'f1199a27af80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week-body',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['body'], ['body-type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['week.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_week-body_id'), 'week-body', ['id'], unique=False)
    op.drop_constraint('week_bodyType_fkey', 'week', type_='foreignkey')
    op.drop_column('week', 'bodyType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week', sa.Column('bodyType', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('week_bodyType_fkey', 'week', 'body-type', ['bodyType'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_week-body_id'), table_name='week-body')
    op.drop_table('week-body')
    # ### end Alembic commands ###
