"""mode

Revision ID: f1199a27af80
Revises: 3cdfc8173d26
Create Date: 2022-02-18 10:59:34.162295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1199a27af80'
down_revision = '3cdfc8173d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week', sa.Column('bodyType', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'week', 'body-type', ['bodyType'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'week', type_='foreignkey')
    op.drop_column('week', 'bodyType')
    # ### end Alembic commands ###
